# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-toml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
        args: ["--line-length", "120"]
        language_version: python3
-   repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "120", "--gitignore", "--combine-as"]
        # additional_dependencies: [toml]
        # exclude: ^.*/?setup\.py$
# -   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
#     rev: v1.3.1
    # hooks:
    # -   id: python-safety-dependencies-check
    #     files: pyproject.toml
    #     args: ["--short-report"]
# -   repo: local
#     hooks:
#       - id: pytest
#         name: Check pytest unit tests pass
#         entry: pdm run duty test
#         pass_filenames: false
#         language: system
#         types: [python]
